[build]
  command = "pip install -r requirements.txt && python build.py"
  publish = "build"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  PIP_VERSION = "21.3.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild" 