[build]
  command = "pip install -r requirements.txt && python build.py"
  publish = "build"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9.18"
  PIP_VERSION = "21.3.1"
  FLASK_APP = "appmy.py"
  FLASK_ENV = "production"
  PYTHONUNBUFFERED = "1"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[build.processing]
  skip_processing = false
  [build.processing.css]
    bundle = true
    minify = true
  [build.processing.js]
    bundle = true
    minify = true
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true 