[build]
  command = "pip install -r requirements.txt && python build.py"
  publish = "build"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_APP = "appmy.py"
  FLASK_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/flask_app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/flask_app"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 